### ISSUE TITLE
XCode 15 / Swift 5.9 Compile error

### ISSUE THREAD

**Issue by reeq-dev** [StreamAMG/streamamg-sdk-ios#24]
Hi. Can't compile in XCode 15 with swift 5.9.

library: 'StreamAMGSDK/PlayKit'

The file `AMGFairPlayLicenseProvider.swift` has error using the `FairPlayLicenseProvider` protocol, method `getLicense`, file `PKMediaEntry.swift`.

<img width="954" alt="image" src="https://github.com/StreamAMG/streamamg-sdk-ios/assets/26365596/c24be536-8448-4494-b953-469940188b9b">

**Comment by francodriansetti** [comment]
@reeq-dev make sure you clean your project and run `pod update`

**Comment by reeq-dev** [comment]
@francodriansetti that did not fix it. The only quick fix from xcode solve the problem in local pods

**Comment by francodriansetti** [comment]
@reeq-dev can you please share your podfile?

**Comment by reeq-dev** [comment]
@francodriansetti what exactly you want to see in my Podfile if there is a simple error inside of library after updating the XCode to 15 (it was fine on previous version)? There is also a simple fix by changing argument from `contentId` to `assetId` as its written in protocol `FairPlayLicenseProvider`:
``` swift
@objc public protocol FairPlayLicenseProvider {
    @objc func getLicense(spc: Data, assetId: String, requestParams: PKRequestParams,
                          callback: @escaping (_ ckc: Data?, _ offlineDuration: TimeInterval, _ error: Error?) -> Void)
}
```

**Comment by curtisbacon** [comment]
@reeq-dev you need to bump the library version of `playkit`: https://github.com/kaltura/playkit-ios/pull/470/files

**Comment by francodriansetti** [comment]
> @francodriansetti what exactly you want to see in my Podfile if there is a simple error inside of library after updating the XCode to 15 (it was fine on previous version)? There is also a simple fix by changing argument from `contentId` to `assetId` as its written in protocol `FairPlayLicenseProvider`:
> 
> ```swift
> @objc public protocol FairPlayLicenseProvider {
>     @objc func getLicense(spc: Data, assetId: String, requestParams: PKRequestParams,
>                           callback: @escaping (_ ckc: Data?, _ offlineDuration: TimeInterval, _ error: Error?) -> Void)
> }
> ```

The latest PlayKit release replaced the field `asstId` with `contentId` please see here https://github.com/kaltura/playkit-ios/blob/242c34ab1435dd50523bc377c37a2b621c62cd74/Classes/Player/Media/PKMediaEntry.swift#L187

Can you please share your pod file so we can try to replicate the error locally? I'm interested to see the AMG SDK version that you are using, platform version for iOS and other configurations you have in the pod file. 


> @reeq-dev you need to bump the library version of `playkit`: https://github.com/kaltura/playkit-ios/pull/470/files

We already using the latest PlayKit version.

**Comment by reeq-dev** [comment]
@francodriansetti we are using Playkit as a dependency of our private library, and for now we are using strict 1.1.8 version:
```ruby
s.dependency "StreamAMGSDK/PlayKit", "1.1.8"
```
I'll check with the latest version if it fixes the error and reply (then close if its fine) to you later

**Comment by reeq-dev** [comment]
The latest version (1.2.7) seems to compile just fine. Thanks everyone
