### ISSUE TITLE
Privacy manifest duplicate

### ISSUE THREAD

**Issue by reeq-dev** [StreamAMG/streamamg-sdk-ios#31]
Hi. As you probably already know, the apple introduced a new rule regarding privacy manifest.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

The PlayKit library or its dependecies have a dependency XCGLogger which use a sensitive api which need to be described in such manifest. The latest XCGLogger has added such PrivacyInfo manifest but made it wrong way so we with our 2 projects faced an error with duplication PrivacyInfo file because we have our own PrivacyInfo file.

The key problem in their podspec file where they marked privacy manifest as:

**XCGLogger.podspec**
`core.resource = '.swift-version', 'Sources/XCGLogger/PrivacyInfo.xcprivacy'`

**ObjcExceptionBridging.podspec**
`core.resource = 'Sources/ObjcExceptionBridging/PrivacyInfo.xcprivacy'`

But since our project based on react-native where the compilation is static, we faced the problem described in official cocoapods documentation: 
https://guides.cocoapods.org/syntax/podspec.html#resources

`we strongly recommend library developers to adopt [resource bundles](http://guides.cocoapods.org/syntax/podspec.html#resource_bundles) as there can be name collisions using the resources attribute`

I've already created an issue in their library. But since this is a dependecy of a stream amg ios sdk you also must know about it.

Issue created in XCGLogger: 
https://github.com/DaveWoodCom/XCGLogger/issues/336

**Comment by StefanoStream** [comment]
Thanks @reeq-dev for your feedback. We are going to update our AMG SDK with Privacy Info very soon.

**Comment by reeq-dev** [comment]
@StefanoStream XCGLogger has fixed their bug regarding "global" privacy manifest so we can compile our projects now. Issue may be closed if you want to

**Comment by StefanoStream** [comment]
Fixed by #32 on version [1.3.2](https://github.com/StreamAMG/streamamg-sdk-ios/releases/tag/1.3.2)

**Comment by StefanoStream** [comment]
Fixed by #32 on version [1.3.2](https://github.com/StreamAMG/streamamg-sdk-ios/releases/tag/1.3.2)
