### ISSUE TITLE
YouboraLib needs to be 6.6.9 for static library support

### ISSUE THREAD

**Issue by nodata** [StreamAMG/streamamg-sdk-ios#9]
I'm integrating StreamAMG-SDK-iOS for use in a react native codebase and need to have the sdk be a static library. 
YouboraLib 6.5.39 sadly does not support that but I've been informed by the guys at NPAW that 6.6.9 does. 

Would it be possible to change the version dependency from 6.5.39 to 6.6.9? It's been days of trying to crowbar the pod in as a dynamic library so far and I'm going absolutely mad.

When I tried to hardcode the latest version... `pod 'YouboraLib', '6.6.9'`

```
In Podfile:
    StreamAMGSDK was resolved to 1.1.5, which depends on
      StreamAMGSDK/PlayKit (= 1.1.5) was resolved to 1.1.5, which depends on
        PlayKitYoubora (= 1.12.0) was resolved to 1.12.0, which depends on
          YouboraLib (= 6.5.39)

    YouboraLib (= 6.6.9)
```

**Comment by francodriansetti** [comment]
@nodata please contact your StreamAMG account manager with your request.

**Comment by nodata** [comment]
Hey @francodriansetti I don't understand what that means... my team just wants to use this cocoapod
